openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0
  description: API for user management in a Todo application

paths:
  /create-user:
    post:
      summary: Create a new user
      description: Endpoint to create a new user in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Unique username for the user
                password:
                  type: string
                  description: Password for the user
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '500':
          description: Server error

  /login:
    post:
      summary: User login
      description: Endpoint for user authentication and token retrieval.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Registered username
                password:
                  type: string
                  description: User's password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Authentication token
        '401':
          description: Unauthorized
        '500':
          description: Server error

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
